### PR TITLE
Added Battleship.Pirate.generate_id

### PR DESCRIPTION
**Pull request by h4cc**
Added Battleship.Pirate.generate_id(amount_words, number_max) for generating game ids like "ahoy-matey-4523".

config.exs was adopted for this type of ids too.

Implements #5

### CODE REVIEW

**Comment by bigardone** [comment]
Awesome! My only concern is that the original `generate_id` function was also generating the random player ids [here](https://github.com/bigardone/phoenix-battleship/blob/master/web/controllers/page_controller.ex#L5). What do you think about having two different functions, one for the player ids and the other for game ids (pirate version)?

**Comment by h4cc** [comment]
Thanks for that info, did not see that. I will have a look on that.

**Comment by bigardone** [comment]
No problem! That id is also for referencing the board agent process so the more random and unique the better.

**Comment by bigardone** [comment]
Hey @h4cc any updates on this or shall I merge it as it is? :)

**Comment by h4cc** [comment]
Pushed latest state. There is now a generate_game_id and generate_player_id. Also a cool generate_name :)

**Comment by bigardone** [comment]
Great job! Merging!

**Pull request merged**
